// src/app/layout.tsx
import './globals.css'
import { Inter, Roboto } from 'next/font/google'
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'] });

export const metadata = {
  title: 'Kat.Codes',
  description: 'Generated by Kat’s handy dandy coding skills',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children} 
      </body>
    </html>
  );
}
