// Cite: Next.js Pages and Layout - File Base Routing - https://nextjs.org/docs/app/getting-started/layouts-and-pages

import { BrowserRouter } from 'react-router-dom'
import './globals.css'
import { Inter, Roboto, Rouge_Script } from 'next/font/google'
import Home from './page'


const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'] });

export const metadata = {
  title: 'Kat.Codes',
  description: 'Generated by kats handy dandy coding skills',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Home />
      </body>

    </html>
  )
}
